import os
import json
import logging
from flask import Flask, render_template, request, jsonify, send_file
from dotenv import load_dotenv

# Import our planner utility
from utils.planner import generate_travel_plan

# PDF generation imports
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

# Load environment variables
load_dotenv()

app = Flask(__name__)
app.secret_key = os.urandom(24)

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class NumberedCanvas(canvas.Canvas):
    """
    Custom canvas to handle two-pass page numbering
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748b")) # slate-500
        
        # Header text
        self.drawString(54, 750, "TravelGPT – Personalized Itinerary")
        self.setStrokeColor(colors.HexColor("#e2e8f0")) # slate-200
        self.setLineWidth(0.5)
        self.line(54, 742, letter[0] - 54, 742)
        
        # Footer text
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 54, 36, page_text)
        self.drawString(54, 36, "Generated by TravelGPT AI Planner")
        self.line(54, 48, letter[0] - 54, 48)
        
        self.restoreState()


@app.route('/')
def index():
    """
    Render home page with the trip planning form
    """
    return render_template('index.html')


@app.route('/result')
def result():
    """
    Render results page. Query parameters are passed to the page, 
    and a JavaScript fetch is triggered on page load.
    """
    # Verify we have at least destination and days
    dest = request.args.get('destination')
    days = request.args.get('days')
    
    if not dest or not days:
        # Redirect to index if parameters are missing
        return render_template('index.html', error="Please fill out the form to plan your trip.")
        
    return render_template('result.html')


@app.route('/api/generate', methods=['POST'])
def api_generate():
    """
    Asynchronous JSON API for generating the trip plan.
    Prevents page timeouts and facilitates a custom loading UI.
    """
    try:
        data = request.json or {}
        
        destination = data.get('destination', '').strip()
        days = int(data.get('days', 3))
        budget = data.get('budget', 'Moderate')
        travelers = int(data.get('travelers', 1))
        style = data.get('style', 'Solo')
        interests = data.get('interests', [])
        transportation = data.get('transportation', 'Public Transit')
        hotel_pref = data.get('hotel_pref', 'Mid-range')
        starting_city = data.get('starting_city', '').strip()
        user_api_key = data.get('api_key', '').strip() # User-supplied API key from UI settings
        
        # Basic validation
        if not destination or not starting_city:
            return jsonify({'success': False, 'error': 'Destination and starting city are required.'}), 400
            
        if days < 1 or days > 14:
            return jsonify({'success': False, 'error': 'Trip duration must be between 1 and 14 days.'}), 400
            
        # Call the planner module
        plan = generate_travel_plan(
            destination=destination,
            days=days,
            budget=budget,
            travelers=travelers,
            style=style,
            interests=interests,
            transportation=transportation,
            hotel_pref=hotel_pref,
            starting_city=starting_city,
            api_key=user_api_key
        )
        
        return jsonify({'success': True, 'plan': plan})
        
    except ValueError as ve:
        logger.error(f"Validation error in generation API: {ve}")
        return jsonify({'success': False, 'error': 'Invalid inputs. Check duration and numbers.'}), 400
    except Exception as e:
        logger.error(f"Unexpected error in generation API: {e}")
        return jsonify({'success': False, 'error': f"Failed to generate plan: {str(e)}"}), 500


@app.route('/api/download-pdf', methods=['POST'])
def api_download_pdf():
    """
    Creates a styled PDF document from the itinerary data sent from the client.
    Returns the file attachment.
    """
    try:
        plan_data = request.json
        if not plan_data:
            return jsonify({'success': False, 'error': 'No plan data provided.'}), 400
            
        dest = plan_data.get('destination', 'Unknown')
        days = plan_data.get('days', 3)
        style = plan_data.get('style', 'Standard')
        budget = plan_data.get('budget', 'Moderate')
        start = plan_data.get('starting_city', 'Home')
        
        buffer = BytesIO()
        
        # Setup document geometry (with margin for custom header/footer)
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'PDFTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=26,
            leading=30,
            textColor=colors.HexColor("#0f172a"), # slate-900
            spaceAfter=6
        )
        
        subtitle_style = ParagraphStyle(
            'PDFSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#64748b"), # slate-500
            spaceAfter=20
        )
        
        h1_style = ParagraphStyle(
            'PDFH1',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=16,
            leading=20,
            textColor=colors.HexColor("#1e3a8a"), # deep blue
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True
        )

        h2_style = ParagraphStyle(
            'PDFH2',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#0f172a"),
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            'PDFBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"), # slate-700
            spaceAfter=6
        )

        bullet_style = ParagraphStyle(
            'PDFBullet',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )
        
        story = []
        
        # Cover / Header
        story.append(Paragraph(f"Itinerary for {dest}", title_style))
        story.append(Paragraph(f"{days}-Day {style} Getaway | Starting from {start} | Budget: {budget}", subtitle_style))
        story.append(Spacer(1, 10))
        
        # Overview stats table
        overview_data = [
            [Paragraph("<b>Destination:</b>", body_style), Paragraph(dest, body_style),
             Paragraph("<b>Duration:</b>", body_style), Paragraph(f"{days} Days", body_style)],
            [Paragraph("<b>Starting City:</b>", body_style), Paragraph(start, body_style),
             Paragraph("<b>Travel Style:</b>", body_style), Paragraph(style, body_style)],
            [Paragraph("<b>Budget Level:</b>", body_style), Paragraph(budget, body_style),
             Paragraph("<b>Travelers:</b>", body_style), Paragraph(str(plan_data.get('travelers', 1)), body_style)]
        ]
        
        t = Table(overview_data, colWidths=[100, 150, 100, 150])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('PADDING', (0,0), (-1,-1), 8),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))
        
        # Weather
        weather_info = plan_data.get('weather', {})
        if weather_info:
            story.append(Paragraph("Weather Forecast & Clothing", h1_style))
            story.append(Paragraph(f"<b>Conditions:</b> {weather_info.get('summary', 'Pleasant')}", body_style))
            story.append(Paragraph(f"<b>Temperature:</b> {weather_info.get('temperature', 'N/A')}", body_style))
            story.append(Paragraph(f"<b>Packing Advice:</b> {weather_info.get('clothing_suggestions', 'N/A')}", body_style))
            story.append(Spacer(1, 15))
            
        # Day-by-Day Itinerary
        story.append(Paragraph("Day-by-Day Itinerary", h1_style))
        for day in plan_data.get('itinerary', []):
            story.append(Paragraph(f"<b>Day {day.get('day')}: Exploration</b>", h2_style))
            
            # Morning
            morn = day.get('morning', {})
            story.append(Paragraph(f"<b>Morning ({morn.get('time', '09:00 AM')}): {morn.get('attraction')}</b>", body_style))
            story.append(Paragraph(morn.get('activity', ''), bullet_style))
            story.append(Paragraph(morn.get('description', ''), bullet_style))
            
            # Afternoon
            aft = day.get('afternoon', {})
            story.append(Paragraph(f"<b>Afternoon ({aft.get('time', '01:30 PM')}): {aft.get('attraction')}</b>", body_style))
            story.append(Paragraph(aft.get('activity', ''), bullet_style))
            story.append(Paragraph(aft.get('description', ''), bullet_style))
            
            # Evening
            eve = day.get('evening', {})
            story.append(Paragraph(f"<b>Evening ({eve.get('time', '06:30 PM')}): {eve.get('attraction')}</b>", body_style))
            story.append(Paragraph(eve.get('activity', ''), bullet_style))
            story.append(Paragraph(eve.get('description', ''), bullet_style))
            
            # Restaurants
            rests = day.get('restaurants', [])
            if rests:
                rest_names = [f"{r.get('name')} ({r.get('type')}: {r.get('description')})" for r in rests]
                story.append(Paragraph(f"<b>Recommended Dining:</b> {', '.join(rest_names)}", body_style))
                
            story.append(Paragraph(f"<i>Travel Time: {day.get('travel_time', 'N/A')}</i>", body_style))
            story.append(Spacer(1, 10))
            
        story.append(PageBreak())
        
        # Budget breakdown
        budget_info = plan_data.get('budget_breakdown', {})
        if budget_info:
            story.append(Paragraph("Estimated Expenses & Budget Suggestions", h1_style))
            curr = budget_info.get('currency', '$')
            
            budget_table_data = [
                [Paragraph("<b>Category</b>", body_style), Paragraph("<b>Estimated Cost</b>", body_style)],
                [Paragraph("Accommodations (Hotel/Stay)", body_style), Paragraph(f"{curr} {budget_info.get('hotel', 0)}", body_style)],
                [Paragraph("Food & Dining", body_style), Paragraph(f"{curr} {budget_info.get('food', 0)}", body_style)],
                [Paragraph("Local Transportation", body_style), Paragraph(f"{curr} {budget_info.get('transport', 0)}", body_style)],
                [Paragraph("Attractions & Activities", body_style), Paragraph(f"{curr} {budget_info.get('attractions', 0)}", body_style)],
                [Paragraph("Shopping & Incidentals", body_style), Paragraph(f"{curr} {budget_info.get('shopping', 0)}", body_style)],
                [Paragraph("<b>Total Estimated Expense</b>", body_style), Paragraph(f"<b>{curr} {budget_info.get('total', 0)}</b>", body_style)]
            ]
            
            bt = Table(budget_table_data, colWidths=[250, 200])
            bt.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f1f5f9")),
                ('PADDING', (0,0), (-1,-1), 6),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor("#e2e8f0")),
            ]))
            story.append(bt)
            story.append(Spacer(1, 15))
            
            story.append(Paragraph("<b>Budget-Saving Suggestions:</b>", h2_style))
            for sug in budget_info.get('suggestions', []):
                story.append(Paragraph(f"• {sug}", bullet_style))
            story.append(Spacer(1, 15))
            
        # Packing list
        packing = plan_data.get('packing_list', {})
        if packing:
            story.append(Paragraph("Recommended Packing List", h1_style))
            for cat, items in packing.items():
                if items:
                    cat_name = cat.replace('_', ' ').capitalize()
                    story.append(Paragraph(f"<b>{cat_name}:</b>", h2_style))
                    story.append(Paragraph(", ".join(items), body_style))
            story.append(Spacer(1, 15))
            
        # Travel Tips
        tips = plan_data.get('travel_tips', {})
        if tips:
            story.append(Paragraph("Essential Travel Tips & Info", h1_style))
            story.append(Paragraph(f"<b>Local Customs:</b> {tips.get('customs', 'N/A')}", body_style))
            story.append(Paragraph(f"<b>Safety Advice:</b> {tips.get('safety', 'N/A')}", body_style))
            story.append(Paragraph(f"<b>Emergency Contacts:</b> {tips.get('emergency_numbers', 'N/A')}", body_style))
            story.append(Paragraph(f"<b>Currency & Payment:</b> {tips.get('currency', 'N/A')}", body_style))
            story.append(Paragraph(f"<b>Language Tips:</b> {tips.get('language', 'N/A')}", body_style))
            story.append(Paragraph(f"<b>Best Foods to Sample:</b> {tips.get('best_foods', 'N/A')}", body_style))
            story.append(Paragraph(f"<b>Things to Avoid:</b> {tips.get('avoid', 'N/A')}", body_style))
            
        # Build PDF using our custom NumberedCanvas for header/footer page numbers
        doc.build(story, canvasmaker=NumberedCanvas)
        
        buffer.seek(0)
        filename = f"{dest.replace(' ', '_')}_Itinerary.pdf"
        return send_file(
            buffer,
            as_attachment=True,
            download_name=filename,
            mimetype='application/pdf'
        )
        
    except Exception as e:
        logger.error(f"Error generating PDF: {e}")
        return jsonify({'success': False, 'error': f"Failed to generate PDF: {str(e)}"}), 500


if __name__ == '__main__':
    app.run(debug=True, host='127.0.0.1', port=5000)
